# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'newdow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon, QPalette, QPixmap, QBrush

basedir = os.path.dirname(__file__)  # 本地路径


class Ui_MainWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(482, 545)
        Form.setWindowIcon(QIcon(os.path.join(basedir, "logo.png")))
        self.set_background_image(Form)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AvatarWidget = AvatarWidget(os.path.join(basedir, "table.png"), Form)
        self.AvatarWidget.setObjectName("AvatarWidget")
        self.verticalLayout_2.addWidget(self.AvatarWidget, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = TitleLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setProperty("pixelFontSize", 17)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.LineEdit = LineEdit(Form)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.PushButton = PushButton(Form)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TitleLabel_2 = TitleLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_2.setFont(font)
        self.TitleLabel_2.setProperty("pixelFontSize", 17)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.horizontalLayout_2.addWidget(self.TitleLabel_2)
        self.menu = RoundMenu(Form)
        self.menu.addAction(Action(QIcon(os.path.join(basedir, "chuankou.svg")), '串口连接断开'))
        self.dropDownPushButton = DropDownPushButton(Form)
        self.dropDownPushButton.setIcon(QIcon(os.path.join(basedir, "chuankou.svg")))
        self.dropDownPushButton.setText('串口连接断开')
        self.dropDownPushButton.setMenu(self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropDownPushButton.sizePolicy().hasHeightForWidth())
        self.dropDownPushButton.setSizePolicy(sizePolicy)
        self.dropDownPushButton.setObjectName("dropDownPushButton")
        self.horizontalLayout_2.addWidget(self.dropDownPushButton)
        self.PushButton_2 = PushButton(Form)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.BodyLabel = TextEdit(Form)
        self.BodyLabel.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setProperty("pixelFontSize", 14)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_2.addWidget(self.BodyLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Avatar下载器"))
        self.TitleLabel.setText(_translate("Form", "路径:"))
        self.PushButton.setText(_translate("Form", "选择文件"))
        self.TitleLabel_2.setText(_translate("Form", "端口:"))
        self.PushButton_2.setText(_translate("Form", "下载程序"))
        self.BodyLabel.setText(_translate("Form", "日志输出:"))

    def set_background_image(self, Form):
        palette = QPalette()
        pixmap = QPixmap(os.path.join(basedir, "screen_bg.png"))  # 将这里替换为你实际的图片路径
        pixmap = pixmap.scaled(Form.size(), Qt.KeepAspectRatioByExpanding)
        brush = QBrush(pixmap)
        palette.setBrush(QPalette.Background, brush)
        Form.setPalette(palette)

from qfluentwidgets import AvatarWidget, BodyLabel, menu, LineEdit, PushButton, TitleLabel, RoundMenu, \
    DropDownPushButton, Action, TextEdit
